# This is a generated file. Not intended for manual editing.
services:
  lab2:
    build:
      context: "E:\\FPTU\\2024_8_FALL\\PRN231\\labs-imp\\lab2"
      dockerfile: "lab2/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app-1/bin/Debug/net8.0/lab2.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "lab2:dev"
    ports: []
    volumes:
    - "C:\\Users\\DELL\\.nuget\\packages:/home/app/.nuget/packages"
    - "E:\\FPTU\\2024_8_FALL\\PRN231\\labs-imp\\lab2\\lab2:/app-1:rw"
    - "E:\\FPTU\\2024_8_FALL\\PRN231\\labs-imp\\lab2:/src:rw"
    working_dir: "/app-1"
